# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate correlation only for ranges where the mask bit has been set
#'
#' @param v1 Input vector 1
#' @param v2 Input vector 2
#' @param mask Mask, each bit that is set will be included in the correlation
#' @param mask_ranges List of start, end tuples for each of the mask groups
#' @return The Pearson correlation between the designated parts of the input vectors
#' @export
masked_corr <- function(v1, v2, mask, mask_ranges) {
    .Call('maskedCorr_masked_corr', PACKAGE = 'maskedCorr', v1, v2, mask, mask_ranges)
}

#' Test if any bit in the input masks is set exactly once
contains_singleton <- function(vs, N_bits) {
    .Call('maskedCorr_contains_singleton', PACKAGE = 'maskedCorr', vs, N_bits)
}

#' count the number of bits set
count_set_bits <- function(vs, N_bits) {
    .Call('maskedCorr_count_set_bits', PACKAGE = 'maskedCorr', vs, N_bits)
}

